Added methods for next tab, previous tab, getting the tab-index, and activating by tab index.
spatie/vue-tabs-component pull request #24
Opened 2017-10-08 21:47 UTC by dsandber

I finally got around to doing the regression tests you requested in #13

2017-10-09 13:44 UTC, freekmurze commented
Conflicts. Could you rebase this againt the current master?

2017-10-09 14:23 UTC, dsandber commented
Can I do it through "resolve conflicts" or is that problematic for some reason?

2017-10-09 15:01 UTC, freekmurze commented
Do it with what suits you best.

2017-10-09 15:36 UTC, dsandber commented
Resolved conflicts.

2017-10-12 11:04 UTC, vesper8 commented
this is beautiful! can't wait to use this in combination with keyboard arrows. thanks for adding it!

2017-10-15 00:02 UTC, freekmurze requested changes
Nice PR!

2017-10-15 00:02 UTC, freekmurze commented on src/components/Tab.vue
> +                let hash_suffix = this.id ? this.id : this.name.toLowerCase().replace(/ /g, '-');
The previous version is more readable to me. Could you revert this?

2017-10-15 00:02 UTC, freekmurze commented on src/components/Tabs.vue
> +                if (setLocationHash) {
Let's let the code breath a little. Add a newline before this line.

2017-10-16 06:33 UTC, sebastiandedeyne requested changes
Looking good! Requested a few more changes before we merge :)

2017-10-16 06:33 UTC, sebastiandedeyne commented on src/components/Tab.vue
> +                let hash_suffix = this.id ? this.id : this.name.toLowerCase().replace(/ /g, '-');
Wouldn't `/\s/g` be a better choice here?

2017-10-16 06:33 UTC, sebastiandedeyne commented on src/components/Tabs.vue
> +            nextTab(wrap = false) {
Could `wrap` be renamed to `cycle` everywhere?

2017-10-16 06:33 UTC, sebastiandedeyne commented on src/components/Tabs.vue
> +            getActiveTabIndex() {
I'd make a computed property out of this

2017-10-16 06:33 UTC, sebastiandedeyne commented on src/components/Tabs.vue
> +                const tab = this.findTab(this.activeTabHash);
And move this to it's own `activeTab` computed prop

2017-10-16 06:33 UTC, sebastiandedeyne commented on src/components/Tabs.vue
> +                let index = this.getActiveTabIndex();
`index` doesn't need to be mutated here, could be a `const`.

```js
const index = this.getActiveTabIndex() + 1;
```

2017-10-16 06:33 UTC, sebastiandedeyne commented on src/components/Tabs.vue
> +                let index = this.getActiveTabIndex();
Same as `nextTab`

2018-02-23 10:12 UTC, sebastiandedeyne commented
Gonna close this for now, feel free to spin up a new PR with the requested feedback if you still want this merged in, no priority for us :)

2018-02-23 10:12 UTC, closed without merging